### ISSUE TITLE
CNN Training File

### ISSUE THREAD

**Issue by RamyaNT** [jingpu/MDig#2]
Hi@jingpu 
I want to have a look at your CNN training file. Though, there are many easy ways to replicate the lean network that you have discussed in your paper, I found your implementation of the CNN a bit challenging.
Firstly, I found that your CNN is a GPU implementation using Theano's sandbox convnet than the usual tensor nnet.
Secondly, the dump file you got has been put into a numpy dictionary format, so that weights can be accessed by parameter keywords.
Thirdly, in order to extract more number of weights, you used the border_mode = 'same' which is not available for CPU - and therefore the image is not resized at the convolution layer but is resized only at the pooling layer.
Finally, the input arrangement and the 4D weights tensor/ the filter shape is not  the regular bc01 arrangement which is implemented in Theano's conv2d but is of type c01b.
I have learnt all the above by analysing the dump file. Ive made futile attempts to create the same training file but with little success. It would be really helpful if you would share the python training file as it would help me in understanding more about training CNNs on GPU.

Regards

**Comment by jingpu** [comment]
Hi@RamyaNT,

Firstly, we didn't use Theano for training. Instead, we use a home-brewed python script adopted from another course project. The script is a bit messing and contains some course related confidential code as well, so we didn't open source this part. However, we did train the network parameters on our laptop CPU.

Second, if you want to use your own environment for training, I will suggest to aim at creating a DeepBeliefSDK compatible 'ntwk' file from your training results instead of trying to match our python dumps. We actually did the same thing, where we dumped our trainning results to MDig/DeepBeliefSDK/data/{mnist_model_reshaped, mean_img}.p file, and used the utility procedure defined in MDig/DeepBeliefSDK/src/tool/mdnet.cpp to convert to MDig/DeepBeliefSDK/data/mdnet.ntwk.

I hope the above is useful.

Regard,

**Comment by RamyaNT** [comment]
Hi@jingpu,

Thanks and your comments have shown me THE PATH. I was moving in a directionless way and was meddling with trivialities. Earlier, it all seemed impossible but now it became easy  and this is a true learning experience. Thank you once again.

Regards
